select  json_object('data'  VALUE to_char(sysdate - interval '10' minute, 'dd/mm/yyyy HH24:mi'),
       'codigo' VALUE json_object('CONVERSAO_PLACA_MERCOSUL' VALUE sum(decode(CODIGO,  'CONVERSAO_PLACA_MERCOSUL', 1, 0) ),
      'SERV_CREDENC' VALUE sum(decode(codigo, 'SERV_CREDENC', 1, 0))    , 
      'TRANSFERENCIA_VEICULO' VALUE sum(decode(codigo, 'TRANSFERENCIA_VEICULO', 1, 0))   ,
      'HABILITACAOA' VALUE sum(decode(codigo, 'HABILITACAOA', 1, 0))   ,
      'HABILITACAO_CNH_RENOVACAO' VALUE sum(decode(codigo, 'HABILITACAO_CNH_RENOVACAO', 1, 0))) )  
     
FROM 
(
 SELECT to_char(a.DH_CRIACAO_CHAVE_QRCODE,'dd/mm/yyyy hh24:MI') DATA,
 CASE b.SF_SER_CODIGO
 WHEN '01100400' THEN 'CONVERSAO_PLACA_MERCOSUL'
WHEN '03816400' THEN 'SERV_CREDENC'
WHEN '01120100' THEN 'TRANSFERENCIA_VEICULO'
WHEN '02201603' THEN 'HABILITACAOA'
WHEN '02100100' THEN 'HABILITACAO_CNH_RENOVACAO'
ELSE 'ID Diferente'
END as codigo
  FROM financeiro.PIX_TB_QRCODE_GERADO a
INNER JOIN FINANCEIRO.PIX_TB_QRCODE_SERVICO b
ON a.CO_CHAVE_QRCODE_GERADO = b.CO_CHAVE_QRCODE_GERADO 
WHERE b.SF_SER_CODIGO IN (01100400,03816400 , 01120100, 02201603, 02100100  )
and a.DH_CRIACAO_CHAVE_QRCODE > sysdate - interval '10' MINUTE
)

